Cries:
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Otamamon
	dba Cry_Kangaskhan
	dba Cry_Guilmon
	dba Cry_Numemon
	dba Cry_Voltorb
	dba Cry_Raremon
	dba Cry_Goblimon
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Tapirmon
	dba Cry_Pidgey
	dba Cry_Nyokomon
	dba Cry_Tokoomon
	dba Cry_Rhydon
	dba Cry_Golemon
	dba Cry_Blastoise
	dba Cry_Angemon
	dba Cry_Motimon
	dba Cry_Minomon
	dba Cry_Gazimon
	dba Cry_Patamon
	dba Cry_Clefairy
	dba Cry_Kunemon
	dba Cry_Lapras
	dba Cry_Wormmon
	dba Cry_Garurumon
	dba Cry_Mushroomon
	dba Cry_Renamon
	dba Cry_Crabmon
	dba Cry_Psyduck
	dba Cry_Tsunomon
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Woodmon
	dba Cry_Marill
	dba Cry_Kokomon
	dba Cry_Demiveemon
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Flamedrmon
	dba Cry_Veemon
	dba Cry_Poromon
	dba Cry_Nyaromon
	dba Cry_Slowking
	dba Cry_Koromon
	dba Cry_Tanemon
	dba Cry_Bukamon
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Gummymon
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Greymon
	dba Cry_Veedramon
	dba Cry_Impmon
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Kudamon
	dba Cry_Donphan
