AnimationPointers:
	dw NyokomonAnimation
	dw PunimonAnimation
	dw BotamonAnimation
	dw GuilmonAnimation
	dw GrowlmonAnimation
	dw TyrannomonAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw MinomonAnimation
	dw WormmonAnimation
	dw StingmonAnimation
	dw MotimonAnimation
	dw TentomonAnimation
	dw KabutrimonAnimation
	dw PidgeyAnimation
	dw PegasusmontoAnimation
	dw PegasusmonAnimation
	dw TsunomonAnimation
	dw GabumonAnimation
	dw TokoomonAnimation
	dw PatamonAnimation
	dw GazimonAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw CandlemonAnimation
	dw MeramonAnimation
	dw PagumonAnimation
	dw DemdevimonAnimation
	dw GoblimonAnimation
	dw OgremonAnimation
	dw VileplumeAnimation
	dw MushroomonAnimation
	dw MushroomonectAnimation
	dw KunemonAnimation
	dw VenomothAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw RenamonAnimation
	dw ArcanineAnimation
	dw BetamonAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw StrikdrmonAnimation
	dw MachampAnimation
	dw LalamonAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GotsumonAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw OtamamonAnimation
	dw SlowbroAnimation
	dw HagurumonAnimation
	dw MagnetonAnimation
	dw FarfetchDAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw TsumemonAnimation
	dw KeramonAnimation
	dw KrysalimonAnimation
	dw ArmdilomonAnimation
	dw TapirmonAnimation
	dw HypnoAnimation
	dw CrabmonAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ChuumonAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw GizamonAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw KuwagamonAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw SwimmonAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw TanemonAnimation
	dw PalmonAnimation
	dw MeganiumAnimation
	dw KoromonAnimation
	dw AgumonAnimation
	dw GreymonAnimation
	dw BukamonAnimation
	dw GomamonAnimation
	dw FeraligatrAnimation
	dw NyaromonAnimation
	dw SalamonAnimation
	dw PoromonAnimation
	dw HawkmonAnimation
	dw GummymonAnimation
	dw TerriermonAnimation
	dw KokomonAnimation
	dw LopmonAnimation
	dw DevimonAnimation
	dw EndigomonAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw DemiveemonAnimation
	dw VeemonAnimation
	dw VeedramonAnimation
	dw ExVeemonAnimation
	dw FlamedrmonAnimation
	dw RaidramonAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw YokomonAnimation
	dw BiyomonAnimation
	dw BirdramonAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw FanbeemonAnimation
	dw WaspmonAnimation
	dw KudamonAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw ElecmonAnimation
	dw LeomonAnimation
	dw QwilfishAnimation
	dw HunybeemonAnimation
	dw ShuckleAnimation
	dw ShadramonAnimation
	dw SneaselAnimation
	dw ImpmonAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw KuramonAnimation
	dw HitmontopAnimation
	dw FloramonAnimation
	dw KiwimonAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
