BitmasksPointers:
	dw NyokomonBitmasks
	dw PunimonBitmasks
	dw BotamonBitmasks
	dw GuilmonBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw MinomonBitmasks
	dw WormmonBitmasks
	dw ButterfreeBitmasks
	dw MotimonBitmasks
	dw TentomonBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw TsunomonBitmasks
	dw RaticateBitmasks
	dw TokoomonBitmasks
	dw FearowBitmasks
	dw GazimonBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw CandlemonBitmasks
	dw WigglytuffBitmasks
	dw PagumonBitmasks
	dw DemdevimonBitmasks
	dw GoblimonBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw MushroomonBitmasks
	dw MushroomonectBitmasks
	dw KunemonBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw LalamonBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw HagurumonBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw TsumemonBitmasks
	dw KeramonBitmasks
	dw GengarBitmasks
	dw ArmdilomonBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw TanemonBitmasks
	dw PalmonBitmasks
	dw MeganiumBitmasks
	dw KoromonBitmasks
	dw AgumonBitmasks
	dw TyphlosionBitmasks
	dw BukamonBitmasks
	dw GomamonBitmasks
	dw FeraligatrBitmasks
	dw NyaromonBitmasks
	dw FurretBitmasks
	dw PoromonBitmasks
	dw HawkmonBitmasks
	dw GummymonBitmasks
	dw TerriermonBitmasks
	dw KokomonBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw DemiveemonBitmasks
	dw VeemonBitmasks
	dw VeedramonBitmasks
	dw ExVeemonBitmasks
	dw FlamedrmonBitmasks
	dw RaidramonBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw YokomonBitmasks
	dw BiyomonBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw FanbeemonBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw ElecmonBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw ImpmonBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw KuramonBitmasks
	dw HitmontopBitmasks
	dw FloramonBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
