BitmasksPointers:
	dw NyokomonBitmasks
	dw PunimonBitmasks
	dw BotamonBitmasks
	dw GuilmonBitmasks
	dw GrowlmonBitmasks
	dw TyrannomonBitmasks
	dw GarurumonBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw MinomonBitmasks
	dw WormmonBitmasks
	dw StingmonBitmasks
	dw MotimonBitmasks
	dw TentomonBitmasks
	dw KabutrimonBitmasks
	dw PidgeyBitmasks
	dw AngemonBitmasks
	dw PegasusmonBitmasks
	dw TsunomonBitmasks
	dw GabumonBitmasks
	dw TokoomonBitmasks
	dw PatamonBitmasks
	dw GazimonBitmasks
	dw ArbokBitmasks
	dw GatomonBitmasks
	dw RaichuBitmasks
	dw NefertimonBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw CandlemonBitmasks
	dw MeramonBitmasks
	dw PagumonBitmasks
	dw DemdevimonBitmasks
	dw GoblimonBitmasks
	dw OgremonBitmasks
	dw VileplumeBitmasks
	dw MushroomonBitmasks
	dw MushroomonectBitmasks
	dw KunemonBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw RenamonBitmasks
	dw KyubimonBitmasks
	dw BetamonBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw WizardmonBitmasks
	dw KadwizardmonBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw StrikdrmonBitmasks
	dw MachampBitmasks
	dw LalamonBitmasks
	dw WoodmonBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GotsumonBitmasks
	dw MonocromonBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw OtamamonBitmasks
	dw SlowbroBitmasks
	dw HagurumonBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw NumemonBitmasks
	dw RaremonBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw TsumemonBitmasks
	dw KeramonBitmasks
	dw KrysalimonBitmasks
	dw ArmdilomonBitmasks
	dw TapirmonBitmasks
	dw BoarmonBitmasks
	dw CrabmonBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ChuumonBitmasks
	dw DigmonBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw ShurimonBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GizamonBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw KuwagamonBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw SwimmonBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorymonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw TanemonBitmasks
	dw PalmonBitmasks
	dw TogemonBitmasks
	dw KoromonBitmasks
	dw AgumonBitmasks
	dw GreymonBitmasks
	dw BukamonBitmasks
	dw GomamonBitmasks
	dw FeraligatrBitmasks
	dw NyaromonBitmasks
	dw SalamonBitmasks
	dw PoromonBitmasks
	dw HawkmonBitmasks
	dw GummymonBitmasks
	dw TerriermonBitmasks
	dw KokomonBitmasks
	dw LopmonBitmasks
	dw DevimonBitmasks
	dw EndigomonBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw DemiveemonBitmasks
	dw VeemonBitmasks
	dw VeedramonBitmasks
	dw ExVeemonBitmasks
	dw FlamedrmonBitmasks
	dw RaidramonBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw YokomonBitmasks
	dw BiyomonBitmasks
	dw BirdramonBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw FanbeemonBitmasks
	dw WaspmonBitmasks
	dw KudamonBitmasks
	dw GligarBitmasks
	dw AnkylomonBitmasks
	dw ElecmonBitmasks
	dw LeomonBitmasks
	dw QwilfishBitmasks
	dw HunybeemonBitmasks
	dw ShuckleBitmasks
	dw ShadramonBitmasks
	dw SneaselBitmasks
	dw ImpmonBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw FrigimonBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porymon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw KuramonBitmasks
	dw HitmontopBitmasks
	dw FloramonBitmasks
	dw KiwimonBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
