FramesPointers:
	dw NyokomonFrames
	dw PunimonFrames
	dw BotamonFrames
	dw GuilmonFrames
	dw GrowlmonFrames
	dw TyrannomonFrames
	dw GarurumonFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw MinomonFrames
	dw WormmonFrames
	dw StingmonFrames
	dw MotimonFrames
	dw TentomonFrames
	dw KabutrimonFrames
	dw PidgeyFrames
	dw AngemonFrames
	dw PegasusmonFrames
	dw TsunomonFrames
	dw GabumonFrames
	dw TokoomonFrames
	dw PatamonFrames
	dw GazimonFrames
	dw ArbokFrames
	dw GatomonFrames
	dw RaichuFrames
	dw NefertimonFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw CandlemonFrames
	dw MeramonFrames
	dw PagumonFrames
	dw DemdevimonFrames
	dw GoblimonFrames
	dw OgremonFrames
	dw VileplumeFrames
	dw MushroomonFrames
	dw MushroomonectFrames
	dw KunemonFrames
	dw VenomothFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw RenamonFrames
	dw KyubimonFrames
	dw BetamonFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw WizardmonFrames
	dw KadwizardmonFrames
	dw AlakazamFrames
	dw MachopFrames
	dw StrikdrmonFrames
	dw MachampFrames
	dw LalamonFrames
	dw WoodmonFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GotsumonFrames
	dw MonocromonFrames
	dw GolemonFrames
	dw PonytaFrames
	dw RapidashFrames
	dw OtamamonFrames
	dw SlowbroFrames
	dw HagurumonFrames
	dw GuardromonFrames
	dw FarfetchDFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw NumemonFrames
	dw RaremonFrames
	dw ShellderFrames
	dw CloysterFrames
	dw TsumemonFrames
	dw KeramonFrames
	dw KrysalimonFrames
	dw ArmdilomonFrames
	dw TapirmonFrames
	dw BoarmonFrames
	dw CrabmonFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ChuumonFrames
	dw DigmonFrames
	dw CuboneFrames
	dw MarowakFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw LickitungFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw ShurimonFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw GizamonFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw KuwagamonFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw SwimmonFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorymonFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoFrames
	dw MewFrames
	dw TanemonFrames
	dw PalmonFrames
	dw TogemonFrames
	dw KoromonFrames
	dw AgumonFrames
	dw GreymonFrames
	dw BukamonFrames
	dw GomamonFrames
	dw FeraligatrFrames
	dw NyaromonFrames
	dw SalamonFrames
	dw PoromonFrames
	dw HawkmonFrames
	dw GummymonFrames
	dw TerriermonFrames
	dw KokomonFrames
	dw LopmonFrames
	dw DevimonFrames
	dw EndigomonFrames
	dw LanturnFrames
	dw PichuFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw DemiveemonFrames
	dw VeemonFrames
	dw VeedramonFrames
	dw ExVeemonFrames
	dw FlamedrmonFrames
	dw RaidramonFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw YokomonFrames
	dw BiyomonFrames
	dw BirdramonFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw UnownFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw FanbeemonFrames
	dw WaspmonFrames
	dw KudamonFrames
	dw GligarFrames
	dw AnkylomonFrames
	dw ElecmonFrames
	dw LeomonFrames
	dw QwilfishFrames
	dw HunybeemonFrames
	dw ShuckleFrames
	dw ShadramonFrames
	dw SneaselFrames
	dw ImpmonFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw FrigimonFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw HalsemonFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porymon2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw KuramonFrames
	dw HitmontopFrames
	dw FloramonFrames
	dw KiwimonFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
