AnimationIdlePointers:
	dw NyokomonAnimationIdle
	dw PunimonAnimationIdle
	dw BotamonAnimationIdle
	dw GuilmonAnimationIdle
	dw GrowlmonAnimationIdle
	dw TyrannomonAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw MinomonAnimationIdle
	dw WormmonAnimationIdle
	dw StingmonAnimationIdle
	dw MotimonAnimationIdle
	dw TentomonAnimationIdle
	dw KabutrimonAnimationIdle
	dw PidgeyAnimationIdle
	dw PegasusmontoAnimationIdle
	dw PegasusmonAnimationIdle
	dw TsunomonAnimationIdle
	dw GabumonAnimationIdle
	dw TokoomonAnimationIdle
	dw PatamonAnimationIdle
	dw GazimonAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw CandlemonAnimationIdle
	dw MeramonAnimationIdle
	dw PagumonAnimationIdle
	dw DemdevimonAnimationIdle
	dw GoblimonAnimationIdle
	dw OgremonAnimationIdle
	dw VileplumeAnimationIdle
	dw MushroomonAnimationIdle
	dw MushroomonectAnimationIdle
	dw KunemonAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw RenamonAnimationIdle
	dw ArcanineAnimationIdle
	dw BetamonAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw StrikdrmonAnimationIdle
	dw MachampAnimationIdle
	dw LalamonAnimationIdle
	dw WoodmonAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GotsumonAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw OtamamonAnimationIdle
	dw SlowbroAnimationIdle
	dw HagurumonAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw TsumemonAnimationIdle
	dw KeramonAnimationIdle
	dw KrysalimonAnimationIdle
	dw ArmdilomonAnimationIdle
	dw TapirmonAnimationIdle
	dw HypnoAnimationIdle
	dw CrabmonAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ChuumonAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw ShurimonAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GizamonAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw KuwagamonAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw SwimmonAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw TanemonAnimationIdle
	dw PalmonAnimationIdle
	dw MeganiumAnimationIdle
	dw KoromonAnimationIdle
	dw AgumonAnimationIdle
	dw GreymonAnimationIdle
	dw BukamonAnimationIdle
	dw GomamonAnimationIdle
	dw FeraligatrAnimationIdle
	dw NyaromonAnimationIdle
	dw SalamonAnimationIdle
	dw PoromonAnimationIdle
	dw HawkmonAnimationIdle
	dw GummymonAnimationIdle
	dw TerriermonAnimationIdle
	dw KokomonAnimationIdle
	dw LopmonAnimationIdle
	dw DevimonAnimationIdle
	dw EndigomonAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw DemiveemonAnimationIdle
	dw VeemonAnimationIdle
	dw VeedramonAnimationIdle
	dw ExVeemonAnimationIdle
	dw FlamedrmonAnimationIdle
	dw RaidramonAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw YokomonAnimationIdle
	dw BiyomonAnimationIdle
	dw BirdramonAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw FanbeemonAnimationIdle
	dw WaspmonAnimationIdle
	dw KudamonAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw ElecmonAnimationIdle
	dw LeomonAnimationIdle
	dw QwilfishAnimationIdle
	dw HunybeemonAnimationIdle
	dw ShuckleAnimationIdle
	dw ShadramonAnimationIdle
	dw SneaselAnimationIdle
	dw ImpmonAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw KuramonAnimationIdle
	dw HitmontopAnimationIdle
	dw FloramonAnimationIdle
	dw KiwimonAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
