INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
MachampFrontpic:     INCBIN "gfx/pokemon/machamp/front.animated.2bpp.lz"
NinetalesFrontpic:   INCBIN "gfx/pokemon/ninetales/front.animated.2bpp.lz"
IkkakumonFrontpic:  INCBIN "gfx/pokemon/ikkakumon/front.animated.2bpp.lz"
NidokingFrontpic:    INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.animated.2bpp.lz"
ArticunoFrontpic:    INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
BotamonFrontpic:    INCBIN "gfx/pokemon/botamon/front.animated.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
GreymonFrontpic:  INCBIN "gfx/pokemon/greymon/front.animated.2bpp.lz"


SECTION "Pics 2", ROMX

ShellmonFrontpic:   INCBIN "gfx/pokemon/shellmon/front.animated.2bpp.lz"
RapidashFrontpic:    INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
TogemonFrontpic:    INCBIN "gfx/pokemon/togemon/front.animated.2bpp.lz"
NidoqueenFrontpic:   INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
HitmonleeFrontpic:   INCBIN "gfx/pokemon/hitmonlee/front.animated.2bpp.lz"
HunybeemonFrontpic:      INCBIN "gfx/pokemon/hunybeemon/front.animated.2bpp.lz"
KabutrimonFrontpic:    INCBIN "gfx/pokemon/kabutrimon/front.animated.2bpp.lz"
KyubimonFrontpic:    INCBIN "gfx/pokemon/kyubimon/front.animated.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
ZapdosFrontpic:      INCBIN "gfx/pokemon/zapdos/front.animated.2bpp.lz"
ArbokFrontpic:       INCBIN "gfx/pokemon/arbok/front.animated.2bpp.lz"
MewtwoFrontpic:      INCBIN "gfx/pokemon/mewtwo/front.animated.2bpp.lz"
PatamonFrontpic:      INCBIN "gfx/pokemon/patamon/front.animated.2bpp.lz"
TyrannomonFrontpic:   INCBIN "gfx/pokemon/tyrannomon/front.animated.2bpp.lz"
AgumonFrontpic:     INCBIN "gfx/pokemon/agumon/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

AnkylomonFrontpic:     INCBIN "gfx/pokemon/ankylomon/front.animated.2bpp.lz"
AlakazamFrontpic:    INCBIN "gfx/pokemon/alakazam/front.animated.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
KangaskhanFrontpic:  INCBIN "gfx/pokemon/kangaskhan/front.animated.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
GolduckFrontpic:     INCBIN "gfx/pokemon/golduck/front.animated.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
PegasusmonFrontpic:     INCBIN "gfx/pokemon/pegasusmon/front.animated.2bpp.lz"
GekomonFrontpic:     INCBIN "gfx/pokemon/gekomon/front.animated.2bpp.lz"
StingmonFrontpic:  INCBIN "gfx/pokemon/stingmon/front.animated.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
CloysterFrontpic:    INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
HalsemonFrontpic:    INCBIN "gfx/pokemon/halsemon/front.animated.2bpp.lz"
DewgongFrontpic:     INCBIN "gfx/pokemon/dewgong/front.animated.2bpp.lz"
VictreebelFrontpic:  INCBIN "gfx/pokemon/victreebel/front.animated.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
PrimeapeFrontpic:    INCBIN "gfx/pokemon/primeape/front.animated.2bpp.lz"
OmastarBackpic:      INCBIN "gfx/pokemon/omastar/back.2bpp.lz"


SECTION "Pics 4", ROMX

DodrioFrontpic:      INCBIN "gfx/pokemon/dodrio/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pokemon/hitmontop/front.animated.2bpp.lz"
ArmdilomonFrontpic:        INCBIN "gfx/pokemon/armdilomon/front.animated.2bpp.lz"
BlisseyFrontpic:     INCBIN "gfx/pokemon/blissey/front.animated.2bpp.lz"
StrikdrmonFrontpic:     INCBIN "gfx/pokemon/strikdrmon/front.animated.2bpp.lz"
KimeramonFrontpic:   INCBIN "gfx/pokemon/kimeramon/front.animated.2bpp.lz"
PoliwrathFrontpic:   INCBIN "gfx/pokemon/poliwrath/front.animated.2bpp.lz"
KuwagamonFrontpic:     INCBIN "gfx/pokemon/kuwagamon/front.animated.2bpp.lz"
AerodactylFrontpic:  INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
SeakingFrontpic:     INCBIN "gfx/pokemon/seaking/front.animated.2bpp.lz"
RaremonFrontpic:         INCBIN "gfx/pokemon/raremon/front.animated.2bpp.lz"
GomamonFrontpic:    INCBIN "gfx/pokemon/gomamon/front.animated.2bpp.lz"
BoarmonFrontpic:       INCBIN "gfx/pokemon/boarmon/front.animated.2bpp.lz"
NidorinoFrontpic:    INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
SandslashFrontpic:   INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

DemdevimonFrontpic:      INCBIN "gfx/pokemon/demdevimon/front.animated.2bpp.lz"
CoelamonFrontpic:     INCBIN "gfx/pokemon/coelamon/front.animated.2bpp.lz"
ChuumonFrontpic:   INCBIN "gfx/pokemon/chuumon/front.animated.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
PersianFrontpic:     INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
StantlerFrontpic:    INCBIN "gfx/pokemon/stantler/front.animated.2bpp.lz"
GabumonFrontpic:    INCBIN "gfx/pokemon/gabumon/front.animated.2bpp.lz"
VenomothFrontpic:    INCBIN "gfx/pokemon/venomoth/front.animated.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
ElectabuzzFrontpic:  INCBIN "gfx/pokemon/electabuzz/front.animated.2bpp.lz"
MantineFrontpic:     INCBIN "gfx/pokemon/mantine/front.animated.2bpp.lz"
LickitungFrontpic:   INCBIN "gfx/pokemon/lickitung/front.animated.2bpp.lz"
KingdraFrontpic:     INCBIN "gfx/pokemon/kingdra/front.animated.2bpp.lz"
GrowlmonFrontpic:  INCBIN "gfx/pokemon/growlmon/front.animated.2bpp.lz"
KadwizardmonFrontpic:     INCBIN "gfx/pokemon/kadwizardmon/front.animated.2bpp.lz"
DigmonFrontpic:   INCBIN "gfx/pokemon/digmon/front.animated.2bpp.lz"
TsumemonFrontpic:      INCBIN "gfx/pokemon/tsumemon/front.animated.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
MushroomonectFrontpic:    INCBIN "gfx/pokemon/mushroomonect/front.animated.2bpp.lz"
MrMimeFrontpic:      INCBIN "gfx/pokemon/mr__mime/front.animated.2bpp.lz"
ShadramonFrontpic:   INCBIN "gfx/pokemon/shadramon/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

LopmonFrontpic:     INCBIN "gfx/pokemon/lopmon/front.animated.2bpp.lz"
HawkmonFrontpic:     INCBIN "gfx/pokemon/hawkmon/front.animated.2bpp.lz"
WartortleFrontpic:   INCBIN "gfx/pokemon/wartortle/front.animated.2bpp.lz"
SeadramonFrontpic:      INCBIN "gfx/pokemon/seadramon/front.animated.2bpp.lz"
GolemonFrontpic:       INCBIN "gfx/pokemon/golemon/front.animated.2bpp.lz"
PoliwhirlFrontpic:   INCBIN "gfx/pokemon/poliwhirl/front.animated.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
NidorinaFrontpic:    INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
VileplumeFrontpic:   INCBIN "gfx/pokemon/vileplume/front.animated.2bpp.lz"
PalmonFrontpic:     INCBIN "gfx/pokemon/palmon/front.animated.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
TentacruelFrontpic:  INCBIN "gfx/pokemon/tentacruel/front.animated.2bpp.lz"
KiwimonFrontpic:      INCBIN "gfx/pokemon/kiwimon/front.animated.2bpp.lz"
BirdramonFrontpic:    INCBIN "gfx/pokemon/birdramon/front.animated.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
VulpixFrontpic:      INCBIN "gfx/pokemon/vulpix/front.animated.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
KudamonFrontpic:   INCBIN "gfx/pokemon/kudamon/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.animated.2bpp.lz"
TapirmonFrontpic:     INCBIN "gfx/pokemon/tapirmon/front.animated.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
BellossomFrontpic:   INCBIN "gfx/pokemon/bellossom/front.animated.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
MeramonFrontpic:  INCBIN "gfx/pokemon/meramon/front.animated.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
SmeargleFrontpic:    INCBIN "gfx/pokemon/smeargle/front.animated.2bpp.lz"
ClefableFrontpic:    INCBIN "gfx/pokemon/clefable/front.animated.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
MonocromonFrontpic:    INCBIN "gfx/pokemon/monocromon/front.animated.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
AngemonFrontpic:   INCBIN "gfx/pokemon/angemon/front.animated.2bpp.lz"
GummymonFrontpic:      INCBIN "gfx/pokemon/gummymon/front.animated.2bpp.lz"
KrysalimonFrontpic:      INCBIN "gfx/pokemon/krysalimon/front.animated.2bpp.lz"
OmastarFrontpic:     INCBIN "gfx/pokemon/omastar/front.animated.2bpp.lz"
PiloswineFrontpic:   INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
DugtrioFrontpic:     INCBIN "gfx/pokemon/dugtrio/front.animated.2bpp.lz"
GuardromonFrontpic:    INCBIN "gfx/pokemon/guardromon/front.animated.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
WaspmonFrontpic:  INCBIN "gfx/pokemon/waspmon/front.animated.2bpp.lz"
VeemonFrontpic:     INCBIN "gfx/pokemon/veemon/front.animated.2bpp.lz"
KangaskhanBackpic:   INCBIN "gfx/pokemon/kangaskhan/back.2bpp.lz"


SECTION "Pics 8", ROMX

SeelFrontpic:        INCBIN "gfx/pokemon/seel/front.animated.2bpp.lz"
DevimonFrontpic:      INCBIN "gfx/pokemon/devimon/front.animated.2bpp.lz"
ChanseyFrontpic:     INCBIN "gfx/pokemon/chansey/front.animated.2bpp.lz"
ShurimonFrontpic:     INCBIN "gfx/pokemon/shurimon/front.animated.2bpp.lz"
ElecmonFrontpic:    INCBIN "gfx/pokemon/elecmon/front.animated.2bpp.lz"
LeomonFrontpic:    INCBIN "gfx/pokemon/leomon/front.animated.2bpp.lz"
MiltankFrontpic:     INCBIN "gfx/pokemon/miltank/front.animated.2bpp.lz"
KeramonFrontpic:     INCBIN "gfx/pokemon/keramon/front.animated.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
TanemonFrontpic:     INCBIN "gfx/pokemon/tanemon/front.animated.2bpp.lz"
GizamonFrontpic:     INCBIN "gfx/pokemon/gizamon/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
ExVeemonFrontpic:        INCBIN "gfx/pokemon/exveemon/front.animated.2bpp.lz"
MewFrontpic:         INCBIN "gfx/pokemon/mew/front.animated.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.animated.2bpp.lz"
JynxFrontpic:        INCBIN "gfx/pokemon/jynx/front.animated.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.animated.2bpp.lz"
TerriermonFrontpic:      INCBIN "gfx/pokemon/terriermon/front.animated.2bpp.lz"
OgremonFrontpic:       INCBIN "gfx/pokemon/ogremon/front.animated.2bpp.lz"
RaidramonFrontpic:     INCBIN "gfx/pokemon/raidramon/front.animated.2bpp.lz"
PunimonFrontpic:     INCBIN "gfx/pokemon/punimon/front.animated.2bpp.lz"
SalamonFrontpic:      INCBIN "gfx/pokemon/salamon/front.animated.2bpp.lz"
KoromonFrontpic:   INCBIN "gfx/pokemon/koromon/front.animated.2bpp.lz"
HitmonchanFrontpic:  INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

GazimonFrontpic:       INCBIN "gfx/pokemon/gazimon/front.animated.2bpp.lz"
SudowoodoFrontpic:   INCBIN "gfx/pokemon/sudowoodo/front.animated.2bpp.lz"
GatomonFrontpic:     INCBIN "gfx/pokemon/gatomon/front.animated.2bpp.lz"
SeadraFrontpic:      INCBIN "gfx/pokemon/seadra/front.animated.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
WoodmonFrontpic:  INCBIN "gfx/pokemon/woodmon/front.animated.2bpp.lz"
BukamonFrontpic:    INCBIN "gfx/pokemon/bukamon/front.animated.2bpp.lz"
CorsolaFrontpic:     INCBIN "gfx/pokemon/corsola/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
MachopFrontpic:      INCBIN "gfx/pokemon/machop/front.animated.2bpp.lz"
EndigomonFrontpic:    INCBIN "gfx/pokemon/endigomon/front.animated.2bpp.lz"
TsunomonFrontpic:     INCBIN "gfx/pokemon/tsunomon/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
TokoomonFrontpic:     INCBIN "gfx/pokemon/tokoomon/front.animated.2bpp.lz"
SwimmonFrontpic:    INCBIN "gfx/pokemon/swimmon/front.animated.2bpp.lz"
GuilmonFrontpic:  INCBIN "gfx/pokemon/guilmon/front.animated.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
NidoranMFrontpic:    INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
PorymonFrontpic:     INCBIN "gfx/pokemon/porymon/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
NumemonFrontpic:      INCBIN "gfx/pokemon/numemon/front.animated.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
MeowthFrontpic:      INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
Porymon2Frontpic:    INCBIN "gfx/pokemon/porymon2/front.animated.2bpp.lz"
NefertimonFrontpic:   INCBIN "gfx/pokemon/nefertimon/front.animated.2bpp.lz"
NidoranFFrontpic:    INCBIN "gfx/pokemon/nidoran_f/front.animated.2bpp.lz"
PidgeyFrontpic:      INCBIN "gfx/pokemon/pidgey/front.animated.2bpp.lz"
MushroomonectBackpic:     INCBIN "gfx/pokemon/mushroomonect/back.2bpp.lz"


SECTION "Pics 10", ROMX

MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
MankeyFrontpic:      INCBIN "gfx/pokemon/mankey/front.animated.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
FanbeemonFrontpic:      INCBIN "gfx/pokemon/fanbeemon/front.animated.2bpp.lz"
CrabmonFrontpic:      INCBIN "gfx/pokemon/crabmon/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
CandlemonFrontpic:  INCBIN "gfx/pokemon/candlemon/front.animated.2bpp.lz"
MushroomonFrontpic:       INCBIN "gfx/pokemon/mushroomon/front.animated.2bpp.lz"
NidokingBackpic:     INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
PsyduckFrontpic:     INCBIN "gfx/pokemon/psyduck/front.animated.2bpp.lz"
GarurumonFrontpic:    INCBIN "gfx/pokemon/garurumon/front.animated.2bpp.lz"
MachampBackpic:      INCBIN "gfx/pokemon/machamp/back.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
KunemonFrontpic:     INCBIN "gfx/pokemon/kunemon/front.animated.2bpp.lz"
DigmonBackpic:    INCBIN "gfx/pokemon/digmon/back.2bpp.lz"
LanturnFrontpic:     INCBIN "gfx/pokemon/lanturn/front.animated.2bpp.lz"
KuramonFrontpic:     INCBIN "gfx/pokemon/kuramon/front.animated.2bpp.lz"
BiyomonFrontpic:    INCBIN "gfx/pokemon/biyomon/front.animated.2bpp.lz"
FlamedrmonFrontpic:      INCBIN "gfx/pokemon/flamedrmon/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
StingmonBackpic:   INCBIN "gfx/pokemon/stingmon/back.2bpp.lz"
PagumonFrontpic:       INCBIN "gfx/pokemon/pagumon/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
AlakazamBackpic:     INCBIN "gfx/pokemon/alakazam/back.2bpp.lz"
AipomFrontpic:       INCBIN "gfx/pokemon/aipom/front.animated.2bpp.lz"
WizardmonFrontpic:        INCBIN "gfx/pokemon/wizardmon/front.animated.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"
CloysterBackpic:     INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"
PoromonFrontpic:    INCBIN "gfx/pokemon/poromon/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"


SECTION "Pics 11", ROMX

DodrioBackpic:       INCBIN "gfx/pokemon/dodrio/back.2bpp.lz"
ClefairyFrontpic:    INCBIN "gfx/pokemon/clefairy/front.animated.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.animated.2bpp.lz"
RenamonFrontpic:   INCBIN "gfx/pokemon/renamon/front.animated.2bpp.lz"
OtamamonFrontpic:    INCBIN "gfx/pokemon/otamamon/front.animated.2bpp.lz"
FloramonFrontpic:    INCBIN "gfx/pokemon/floramon/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
VenomothBackpic:     INCBIN "gfx/pokemon/venomoth/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
OmanyteFrontpic:     INCBIN "gfx/pokemon/omanyte/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
LalamonFrontpic:  INCBIN "gfx/pokemon/lalamon/front.animated.2bpp.lz"
ShellderFrontpic:    INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
TentacoolFrontpic:   INCBIN "gfx/pokemon/tentacool/front.animated.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.animated.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
NinetalesBackpic:    INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
ClefableBackpic:     INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
DoduoFrontpic:       INCBIN "gfx/pokemon/doduo/front.animated.2bpp.lz"
IkkakumonBackpic:   INCBIN "gfx/pokemon/ikkakumon/back.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
GuardromonBackpic:     INCBIN "gfx/pokemon/guardromon/back.2bpp.lz"
SubmarimonFrontpic:    INCBIN "gfx/pokemon/submarimon/front.animated.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
KiwimonBackpic:       INCBIN "gfx/pokemon/kiwimon/back.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
CrabmonBackpic:       INCBIN "gfx/pokemon/crabmon/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"


SECTION "Pics 12", ROMX

BotamonBackpic:     INCBIN "gfx/pokemon/botamon/back.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
SandslashBackpic:    INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
SeadraBackpic:       INCBIN "gfx/pokemon/seadra/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
NidoranMBackpic:     INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
GummymonBackpic:       INCBIN "gfx/pokemon/gummymon/back.2bpp.lz"
KoromonBackpic:    INCBIN "gfx/pokemon/koromon/back.2bpp.lz"
PalmonBackpic:      INCBIN "gfx/pokemon/palmon/back.2bpp.lz"
GoblimonFrontpic:      INCBIN "gfx/pokemon/goblimon/front.animated.2bpp.lz"
RapidashBackpic:     INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
DoduoBackpic:        INCBIN "gfx/pokemon/doduo/back.2bpp.lz"
YokomonFrontpic:      INCBIN "gfx/pokemon/yokomon/front.animated.2bpp.lz"
MankeyBackpic:       INCBIN "gfx/pokemon/mankey/back.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
BoarmonBackpic:        INCBIN "gfx/pokemon/boarmon/back.2bpp.lz"
AgumonBackpic:      INCBIN "gfx/pokemon/agumon/back.2bpp.lz"
GomamonBackpic:     INCBIN "gfx/pokemon/gomamon/back.2bpp.lz"
NefertimonBackpic:    INCBIN "gfx/pokemon/nefertimon/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
ShellderBackpic:     INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
PagumonBackpic:        INCBIN "gfx/pokemon/pagumon/back.2bpp.lz"
ImpmonFrontpic:   INCBIN "gfx/pokemon/impmon/front.animated.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
OgremonBackpic:        INCBIN "gfx/pokemon/ogremon/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
KabutrimonBackpic:     INCBIN "gfx/pokemon/kabutrimon/back.2bpp.lz"
KyubimonBackpic:     INCBIN "gfx/pokemon/kyubimon/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
GizamonBackpic:      INCBIN "gfx/pokemon/gizamon/back.2bpp.lz"
NyokomonFrontpic:   INCBIN "gfx/pokemon/nyokomon/front.animated.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"


SECTION "Pics 13", ROMX

OmanyteBackpic:      INCBIN "gfx/pokemon/omanyte/back.2bpp.lz"
PidgeyBackpic:       INCBIN "gfx/pokemon/pidgey/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
SubmarimonBackpic:     INCBIN "gfx/pokemon/submarimon/back.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
GreymonBackpic:   INCBIN "gfx/pokemon/greymon/back.2bpp.lz"
GrowlmonBackpic:   INCBIN "gfx/pokemon/growlmon/back.2bpp.lz"
NidoqueenBackpic:    INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
ElectabuzzBackpic:   INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
TerriermonBackpic:       INCBIN "gfx/pokemon/terriermon/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
ShadramonBackpic:    INCBIN "gfx/pokemon/shadramon/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
MiltankBackpic:      INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
AnkylomonBackpic:      INCBIN "gfx/pokemon/ankylomon/back.2bpp.lz"
PersianBackpic:      INCBIN "gfx/pokemon/persian/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
ShuckleFrontpic:     INCBIN "gfx/pokemon/shuckle/front.animated.2bpp.lz"
PonytaBackpic:       INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.animated.2bpp.lz"
BetamonFrontpic:     INCBIN "gfx/pokemon/betamon/front.animated.2bpp.lz"
ArmdilomonBackpic:         INCBIN "gfx/pokemon/armdilomon/back.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
NidorinaBackpic:     INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
TentacruelBackpic:   INCBIN "gfx/pokemon/tentacruel/back.2bpp.lz"
RenamonBackpic:    INCBIN "gfx/pokemon/renamon/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
StrikdrmonBackpic:      INCBIN "gfx/pokemon/strikdrmon/back.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
PoliwrathBackpic:    INCBIN "gfx/pokemon/poliwrath/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
NidorinoBackpic:     INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
ElectrodeFrontpic:   INCBIN "gfx/pokemon/electrode/front.animated.2bpp.lz"


SECTION "Pics 14", ROMX

SudowoodoBackpic:    INCBIN "gfx/pokemon/sudowoodo/back.2bpp.lz"
NyaromonFrontpic:     INCBIN "gfx/pokemon/nyaromon/front.animated.2bpp.lz"
VeemonBackpic:      INCBIN "gfx/pokemon/veemon/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
GotsumonBackpic:      INCBIN "gfx/pokemon/gotsumon/back.2bpp.lz"
KuwagamonBackpic:      INCBIN "gfx/pokemon/kuwagamon/back.2bpp.lz"
VileplumeBackpic:    INCBIN "gfx/pokemon/vileplume/back.2bpp.lz"
HitmonchanBackpic:   INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"
BirdramonBackpic:     INCBIN "gfx/pokemon/birdramon/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
ShellmonBackpic:    INCBIN "gfx/pokemon/shellmon/back.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
KuramonBackpic:      INCBIN "gfx/pokemon/kuramon/back.2bpp.lz"
GotsumonFrontpic:     INCBIN "gfx/pokemon/gotsumon/front.animated.2bpp.lz"
HunybeemonBackpic:       INCBIN "gfx/pokemon/hunybeemon/back.2bpp.lz"
GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
StantlerBackpic:     INCBIN "gfx/pokemon/stantler/back.2bpp.lz"
SmeargleBackpic:     INCBIN "gfx/pokemon/smeargle/back.2bpp.lz"
TyrannomonBackpic:    INCBIN "gfx/pokemon/tyrannomon/back.2bpp.lz"
KadwizardmonBackpic:      INCBIN "gfx/pokemon/kadwizardmon/back.2bpp.lz"
PrimeapeBackpic:     INCBIN "gfx/pokemon/primeape/back.2bpp.lz"
SalamonBackpic:       INCBIN "gfx/pokemon/salamon/back.2bpp.lz"
WartortleBackpic:    INCBIN "gfx/pokemon/wartortle/back.2bpp.lz"
ChuumonBackpic:    INCBIN "gfx/pokemon/chuumon/back.2bpp.lz"
IgglybuffFrontpic:   INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
GabumonBackpic:     INCBIN "gfx/pokemon/gabumon/back.2bpp.lz"
VulpixBackpic:       INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
GazimonBackpic:        INCBIN "gfx/pokemon/gazimon/back.2bpp.lz"
SeakingBackpic:      INCBIN "gfx/pokemon/seaking/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
PsyduckBackpic:      INCBIN "gfx/pokemon/psyduck/back.2bpp.lz"
GatomonBackpic:      INCBIN "gfx/pokemon/gatomon/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
FlamedrmonBackpic:       INCBIN "gfx/pokemon/flamedrmon/back.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
KingdraBackpic:      INCBIN "gfx/pokemon/kingdra/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
WooperFrontpic:      INCBIN "gfx/pokemon/wooper/front.animated.2bpp.lz"
ClefairyBackpic:     INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
KunemonBackpic:      INCBIN "gfx/pokemon/kunemon/back.2bpp.lz"
BellossomBackpic:    INCBIN "gfx/pokemon/bellossom/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
FrigimonBackpic:       INCBIN "gfx/pokemon/frigimon/back.2bpp.lz"


SECTION "Pics 15", ROMX

MewtwoBackpic:       INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
DiglettFrontpic:     INCBIN "gfx/pokemon/diglett/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
RaremonBackpic:          INCBIN "gfx/pokemon/raremon/back.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
SwimmonBackpic:     INCBIN "gfx/pokemon/swimmon/back.2bpp.lz"
LopmonBackpic:      INCBIN "gfx/pokemon/lopmon/back.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
PunimonBackpic:      INCBIN "gfx/pokemon/punimon/back.2bpp.lz"
GekomonBackpic:      INCBIN "gfx/pokemon/gekomon/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
GolduckBackpic:      INCBIN "gfx/pokemon/golduck/back.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
HorseaFrontpic:      INCBIN "gfx/pokemon/horsea/front.animated.2bpp.lz"
PegasusmonBackpic:      INCBIN "gfx/pokemon/pegasusmon/back.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
PoliwhirlBackpic:    INCBIN "gfx/pokemon/poliwhirl/back.2bpp.lz"
MewBackpic:          INCBIN "gfx/pokemon/mew/back.2bpp.lz"
MachopBackpic:       INCBIN "gfx/pokemon/machop/back.2bpp.lz"
WizardmonBackpic:         INCBIN "gfx/pokemon/wizardmon/back.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
TentomonFrontpic:      INCBIN "gfx/pokemon/tentomon/front.animated.2bpp.lz"
DugtrioBackpic:      INCBIN "gfx/pokemon/dugtrio/back.2bpp.lz"
WoodmonBackpic:   INCBIN "gfx/pokemon/woodmon/back.2bpp.lz"
NidoranFBackpic:     INCBIN "gfx/pokemon/nidoran_f/back.2bpp.lz"
MonocromonBackpic:     INCBIN "gfx/pokemon/monocromon/back.2bpp.lz"
AipomBackpic:        INCBIN "gfx/pokemon/aipom/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
MotimonFrontpic:      INCBIN "gfx/pokemon/motimon/front.animated.2bpp.lz"
BukamonBackpic:     INCBIN "gfx/pokemon/bukamon/back.2bpp.lz"
ElecmonBackpic:     INCBIN "gfx/pokemon/elecmon/back.2bpp.lz"
CoelamonBackpic:      INCBIN "gfx/pokemon/coelamon/back.2bpp.lz"
KrysalimonBackpic:       INCBIN "gfx/pokemon/krysalimon/back.2bpp.lz"
TsunomonBackpic:      INCBIN "gfx/pokemon/tsunomon/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
HagurumonFrontpic:   INCBIN "gfx/pokemon/hagurumon/front.animated.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
HagurumonBackpic:    INCBIN "gfx/pokemon/hagurumon/back.2bpp.lz"


SECTION "Pics 16", ROMX

PoromonBackpic:     INCBIN "gfx/pokemon/poromon/back.2bpp.lz"
HawkmonBackpic:      INCBIN "gfx/pokemon/hawkmon/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
VictreebelBackpic:   INCBIN "gfx/pokemon/victreebel/back.2bpp.lz"
MeowthBackpic:       INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
TogemonBackpic:     INCBIN "gfx/pokemon/togemon/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
LickitungBackpic:    INCBIN "gfx/pokemon/lickitung/back.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
KeramonBackpic:      INCBIN "gfx/pokemon/keramon/back.2bpp.lz"
ExVeemonBackpic:         INCBIN "gfx/pokemon/exveemon/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
Porymon2Backpic:     INCBIN "gfx/pokemon/porymon2/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
FanbeemonBackpic:       INCBIN "gfx/pokemon/fanbeemon/back.2bpp.lz"
WormmonFrontpic:     INCBIN "gfx/pokemon/wormmon/front.animated.2bpp.lz"
SeelBackpic:         INCBIN "gfx/pokemon/seel/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
MinomonFrontpic:    INCBIN "gfx/pokemon/minomon/front.animated.2bpp.lz"
YokomonBackpic:       INCBIN "gfx/pokemon/yokomon/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
LeomonBackpic:     INCBIN "gfx/pokemon/leomon/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
TokoomonBackpic:      INCBIN "gfx/pokemon/tokoomon/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
SeadramonBackpic:       INCBIN "gfx/pokemon/seadramon/back.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
ZapdosBackpic:       INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
TanemonBackpic:      INCBIN "gfx/pokemon/tanemon/back.2bpp.lz"
CorsolaBackpic:      INCBIN "gfx/pokemon/corsola/back.2bpp.lz"
EndigomonBackpic:     INCBIN "gfx/pokemon/endigomon/back.2bpp.lz"
ChanseyBackpic:      INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
BiyomonBackpic:     INCBIN "gfx/pokemon/biyomon/back.2bpp.lz"
KokomonFrontpic:    INCBIN "gfx/pokemon/kokomon/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
GuilmonBackpic:   INCBIN "gfx/pokemon/guilmon/back.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
FrigimonFrontpic:      INCBIN "gfx/pokemon/frigimon/front.animated.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
PorymonBackpic:      INCBIN "gfx/pokemon/porymon/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"


SECTION "Pics 17", ROMX

MushroomonBackpic:        INCBIN "gfx/pokemon/mushroomon/back.2bpp.lz"
VaporeonBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
TentacoolBackpic:    INCBIN "gfx/pokemon/tentacool/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
NyokomonBackpic:    INCBIN "gfx/pokemon/nyokomon/back.2bpp.lz"
FloramonBackpic:     INCBIN "gfx/pokemon/floramon/back.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
LalamonBackpic:   INCBIN "gfx/pokemon/lalamon/back.2bpp.lz"
NumemonBackpic:       INCBIN "gfx/pokemon/numemon/back.2bpp.lz"
LanturnBackpic:      INCBIN "gfx/pokemon/lanturn/back.2bpp.lz"
AngemonBackpic:    INCBIN "gfx/pokemon/angemon/back.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
MrMimeBackpic:       INCBIN "gfx/pokemon/mr__mime/back.2bpp.lz"
VoltorbFrontpic:     INCBIN "gfx/pokemon/voltorb/front.animated.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
ArbokBackpic:        INCBIN "gfx/pokemon/arbok/back.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
KimeramonBackpic:    INCBIN "gfx/pokemon/kimeramon/back.2bpp.lz"
HitmonleeBackpic:    INCBIN "gfx/pokemon/hitmonlee/back.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
ImpmonBackpic:    INCBIN "gfx/pokemon/impmon/back.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
TentomonBackpic:       INCBIN "gfx/pokemon/tentomon/back.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
DevimonBackpic:       INCBIN "gfx/pokemon/devimon/back.2bpp.lz"
BlisseyBackpic:      INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
IgglybuffBackpic:    INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
HorseaBackpic:       INCBIN "gfx/pokemon/horsea/back.2bpp.lz"
NyaromonBackpic:      INCBIN "gfx/pokemon/nyaromon/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
MeramonBackpic:   INCBIN "gfx/pokemon/meramon/back.2bpp.lz"
ArticunoBackpic:     INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
MotimonBackpic:       INCBIN "gfx/pokemon/motimon/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
TapirmonBackpic:      INCBIN "gfx/pokemon/tapirmon/back.2bpp.lz"
TsumemonBackpic:       INCBIN "gfx/pokemon/tsumemon/back.2bpp.lz"
PatamonBackpic:       INCBIN "gfx/pokemon/patamon/back.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
ElectrodeBackpic:    INCBIN "gfx/pokemon/electrode/back.2bpp.lz"
HalsemonBackpic:     INCBIN "gfx/pokemon/halsemon/back.2bpp.lz"
WormmonBackpic:      INCBIN "gfx/pokemon/wormmon/back.2bpp.lz"
CandlemonBackpic:   INCBIN "gfx/pokemon/candlemon/back.2bpp.lz"
GoblimonBackpic:       INCBIN "gfx/pokemon/goblimon/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"


SECTION "Pics 18", ROMX

KokomonBackpic:     INCBIN "gfx/pokemon/kokomon/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
BetamonBackpic:      INCBIN "gfx/pokemon/betamon/back.2bpp.lz"
GarurumonBackpic:     INCBIN "gfx/pokemon/garurumon/back.2bpp.lz"
ShuckleBackpic:      INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
DewgongBackpic:      INCBIN "gfx/pokemon/dewgong/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
OtamamonBackpic:     INCBIN "gfx/pokemon/otamamon/back.2bpp.lz"
KudamonBackpic:    INCBIN "gfx/pokemon/kudamon/back.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
ShurimonBackpic:      INCBIN "gfx/pokemon/shurimon/back.2bpp.lz"
VoltorbBackpic:      INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
MantineBackpic:      INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
PiloswineBackpic:    INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
GolemonBackpic:        INCBIN "gfx/pokemon/golemon/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
DiglettBackpic:      INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
JynxBackpic:         INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
DemdevimonBackpic:       INCBIN "gfx/pokemon/demdevimon/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
WaspmonBackpic:   INCBIN "gfx/pokemon/waspmon/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


SECTION "Pics 19", ROMX

; Seems to be an accidental copy of the previous bank

INCBIN "gfx/pokemon/kokomon/back.2bpp.lz"
INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
INCBIN "gfx/pokemon/betamon/back.2bpp.lz"
INCBIN "gfx/pokemon/garurumon/back.2bpp.lz"
INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
INCBIN "gfx/pokemon/dewgong/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/otamamon/back.2bpp.lz"
INCBIN "gfx/pokemon/kudamon/back.2bpp.lz"
INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/shurimon/back.2bpp.lz"
INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/veedramon/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/golemon/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
INCBIN "gfx/pokemon/demdevimon/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
INCBIN "gfx/pokemon/waspmon/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX
VeedramonFrontpic:   INCBIN "gfx/pokemon/veedramon/front.animated.2bpp.lz"
DemiveemonFrontpic:  INCBIN "gfx/pokemon/demiveemon/front.animated.2bpp.lz"
DemiveemonBackpic:   INCBIN "gfx/pokemon/demiveemon/back.2bpp.lz"
VeedramonBackpic:    INCBIN "gfx/pokemon/veedramon/back.2bpp.lz"
RaidramonBackpic:    INCBIN "gfx/pokemon/raidramon/back.2bpp.lz"
MinomonBackpic:      INCBIN "gfx/pokemon/minomon/back.2bpp.lz"

SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
